-- =============================================================================
-- Migration 056: backfill regulations.regulatory_endpoints and endpoint_quote
-- =============================================================================

BEGIN;

UPDATE regulations r
SET
  regulatory_endpoints = v.ids,
  endpoint_quote = v.quote
FROM (VALUES
  (1, ARRAY[10]::int[], 'Irritação e corrosão da pele'),
  (2, ARRAY[14]::int[], NULL),
  (5, ARRAY[10]::int[], 'Irritação e corrosão da pele'),
  (6, ARRAY[10]::int[], NULL),
  (7, ARRAY[10]::int[], 'Irritação e corrosão da pele'),
  (8, ARRAY[10]::int[], NULL),
  (9, ARRAY[10]::int[], 'Irritação e corrosão da pele'),
  (10, ARRAY[10]::int[], NULL),
  (11, ARRAY[14]::int[], 'Irritação e corrosão ocular'),
  (12, ARRAY[14]::int[], NULL),
  (13, ARRAY[14]::int[], 'Irritação e corrosão ocular'),
  (14, ARRAY[14]::int[], NULL),
  (15, ARRAY[14]::int[], 'Irritação e corrosão ocular'),
  (16, ARRAY[22]::int[], NULL),
  (17, ARRAY[17]::int[], NULL),
  (18, ARRAY[20]::int[], NULL),
  (19, ARRAY[20]::int[], NULL),
  (20, ARRAY[12]::int[], NULL),
  (21, ARRAY[20]::int[], 'Sensibilização cutânea'),
  (22, ARRAY[25]::int[], NULL),
  (23, ARRAY[20]::int[], 'Sensibilização cutânea'),
  (24, ARRAY[20]::int[], NULL),
  (25, ARRAY[20]::int[], 'Sensibilização cutânea'),
  (26, ARRAY[48]::int[], NULL),
  (27, ARRAY[12]::int[], 'Fototoxicidade'),
  (28, ARRAY[10]::int[], NULL),
  (29, ARRAY[23]::int[], 'Mutagenicidade'),
  (30, ARRAY[3]::int[], NULL),
  (31, ARRAY[23]::int[], 'Mutagenicidade'),
  (32, ARRAY[17]::int[], NULL),
  (33, ARRAY[22]::int[], 'Genotoxicidade'),
  (34, ARRAY[17]::int[], NULL),
  (35, ARRAY[48]::int[], 'Contaminação pirogênica em produtos injetáveis'),
  (37, ARRAY[3]::int[], 'Absorção cutânea'),
  (38, ARRAY[25]::int[], NULL),
  (39, ARRAY[17]::int[], 'Toxicidade aguda'),
  (40, ARRAY[14]::int[], NULL),
  (41, ARRAY[17]::int[], 'Toxicidade aguda'),
  (42, ARRAY[20]::int[], NULL),
  (43, ARRAY[17]::int[], 'Toxicidade aguda'),
  (44, ARRAY[20]::int[], NULL),
  (45, ARRAY[17]::int[], 'Toxicidade aguda'),
  (46, ARRAY[14]::int[], NULL),
  (47, ARRAY[38]::int[], NULL),
  (48, ARRAY[48]::int[], 'Contaminação pirogênica em produtos injetáveis'),
  (53, ARRAY[15]::int[], 'Danos oculares severos e irritação ocular'),
  (54, ARRAY[48]::int[], NULL),
  (55, ARRAY[54]::int[], 'Diagnóstico da raiva animal'),
  (56, ARRAY[54]::int[], 'Diagnóstico da raiva animal'),
  (57, ARRAY[54]::int[], 'Diagnóstico da raiva animal'),
  (62, ARRAY[17]::int[], NULL),
  (63, ARRAY[23]::int[], NULL),
  (64, ARRAY[33]::int[], 'Efeitos estrogênicos'),
  (66, ARRAY[23]::int[], NULL),
  (67, ARRAY[32]::int[], 'Efeitos endócrinos'),
  (68, ARRAY[33]::int[], NULL),
  (69, ARRAY[33]::int[], 'Efeitos estrogênicos'),
  (70, ARRAY[32]::int[], NULL),
  (72, ARRAY[23]::int[], 'Mutagenicidade'),
  (73, ARRAY[33]::int[], NULL),
  (75, ARRAY[23]::int[], 'Mutagenicidade'),
  (76, ARRAY[23]::int[], NULL),
  (77, ARRAY[14, 15]::int[], 'Irritação/corrosão ocular'),
  (78, ARRAY[23]::int[], NULL),
  (79, ARRAY[14, 15]::int[], 'Irritação/corrosão ocular'),
  (80, ARRAY[14, 15]::int[], NULL),
  (81, ARRAY[37]::int[], 'Fotorreatividade'),
  (82, ARRAY[14, 15]::int[], NULL),
  (83, ARRAY[38]::int[], 'Efeitos em sistemas bióticos'),
  (84, ARRAY[37]::int[], NULL),
  (85, ARRAY[38]::int[], 'Efeitos em sistemas bióticos'),
  (86, ARRAY[38]::int[], NULL),
  (88, ARRAY[38]::int[], 'Efeitos em sistemas bióticos'),
  (89, ARRAY[38]::int[], NULL),
  (90, ARRAY[38]::int[], 'Efeitos em sistemas bióticos'),
  (91, ARRAY[50]::int[], 'Detecção de endotoxinas bacterianas'),
  (92, ARRAY[54]::int[], 'Diagnóstico da raiva animal'),
  (93, ARRAY[14]::int[], 'Irritação e corrosão ocular'),
  (95, ARRAY[20]::int[], 'Sensibilização dérmica'),
  (96, ARRAY[34]::int[], 'Efeitos androgênicos'),
  (97, ARRAY[14]::int[], 'Irritação e corrosão ocular'),
  (99, ARRAY[20]::int[], 'Sensibilização cutânea'),
  (100, ARRAY[20]::int[], 'Sensibilização cutânea'),
  (101, ARRAY[25]::int[], 'Toxicidade reprodutiva'),
  (102, ARRAY[25]::int[], 'Toxicidade reprodutiva'),
  (103, ARRAY[38]::int[], NULL)
) AS v(id, ids, quote)
WHERE r.id = v.id;

COMMIT;
